# Generated by Django 3.1.7 on 2021-05-24 20:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', pgcrypto.fields.EncryptedDateField(blank=True, charset='utf-8', check_armor=True, cipher='aes', null=True, versioned=False)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('phone', pgcrypto.fields.EncryptedCharField(charset='utf-8', check_armor=True, cipher='aes', validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон', versioned=False)),
                ('address', pgcrypto.fields.EncryptedCharField(blank=True, charset='utf-8', check_armor=True, cipher='aes', null=True, versioned=False)),
                ('postal_code', pgcrypto.fields.EncryptedCharField(blank=True, charset='utf-8', check_armor=True, cipher='aes', null=True, versioned=False)),
                ('city', pgcrypto.fields.EncryptedCharField(blank=True, charset='utf-8', check_armor=True, cipher='aes', null=True, versioned=False)),
                ('region', pgcrypto.fields.EncryptedCharField(blank=True, charset='utf-8', check_armor=True, cipher='aes', null=True, versioned=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
